-- ============================================================================
-- Versiebeheer + wijzigingsdatum voor ingredients
--
-- Doel: dezelfde versiebeheer-aanpak als recipes (versie_major/versie_minor,
-- een group-id die alle versies van hetzelfde ingrediënt verbindt, en een
-- revisie-logtabel met datum/door/wijziging), plus een betrouwbare
-- "laatst gewijzigd"-datum voor het overzicht.
--
-- Bewuste keuze: de bestaande operationele status (actief/inactief/
-- uitgefaseerd) blijft ongemoeid -- we voegen GEEN 'gearchiveerd' toe aan die
-- kolom (in tegenstelling tot recipes.status, dat die twee dingen combineert).
-- In plaats daarvan komt er een aparte kolom `versie_status` die alleen
-- aangeeft of deze rij de huidige versie is of een gearchiveerde oudere
-- versie. Zo blijft "is dit ingrediënt nog leverbaar" volledig los staan van
-- "is dit de nieuwste versie van dit ingrediënt".
--
-- Alles hieronder is additief/idempotent (IF NOT EXISTS overal), dus veilig
-- om automatisch te draaien.
-- ============================================================================

alter table ingredients add column if not exists versie_major integer not null default 1;
alter table ingredients add column if not exists versie_minor integer not null default 0;
alter table ingredients add column if not exists ingredient_group_id uuid not null default gen_random_uuid();
alter table ingredients add column if not exists versie_status text not null default 'huidig';

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'ingredients_versie_status_check'
  ) then
    alter table ingredients add constraint ingredients_versie_status_check
      check (versie_status in ('huidig', 'gearchiveerd'));
  end if;
end $$;

alter table ingredients add column if not exists aangemaakt_op timestamptz not null default now();
alter table ingredients add column if not exists aangemaakt_door uuid references gebruikers(id);
alter table ingredients add column if not exists gewijzigd_op timestamptz not null default now();
alter table ingredients add column if not exists gewijzigd_door uuid references gebruikers(id);

create index if not exists idx_ingredients_group_id on ingredients (ingredient_group_id);

-- Auto-update gewijzigd_op bij elke UPDATE, zodat de app dit nooit zelf
-- expliciet hoeft mee te sturen (zelfde patroon als de aanname die al voor
-- recipes.gewijzigd_op gemaakt was).
create or replace function set_ingredients_gewijzigd_op()
returns trigger as $$
begin
  new.gewijzigd_op = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_ingredients_gewijzigd_op on ingredients;
create trigger trg_ingredients_gewijzigd_op
  before update on ingredients
  for each row execute function set_ingredients_gewijzigd_op();

-- Revisie-log, één-op-één qua vorm met recipe_revisies.
create table if not exists ingredient_revisies (
  id bigint generated by default as identity primary key,
  ingredient_id bigint not null references ingredients(id),
  versie_major integer not null,
  versie_minor integer not null,
  datum date not null default current_date,
  door text,
  wijziging text,
  gebruiker_id uuid references gebruikers(id),
  aangemaakt_op timestamptz not null default now()
);

create index if not exists idx_ingredient_revisies_ingredient_id
  on ingredient_revisies (ingredient_id);

alter table ingredient_revisies enable row level security;

drop policy if exists "ingredient_revisies_select_authenticated" on ingredient_revisies;
create policy "ingredient_revisies_select_authenticated"
  on ingredient_revisies for select
  to authenticated
  using (true);

drop policy if exists "ingredient_revisies_insert_editor_of_hoger" on ingredient_revisies;
create policy "ingredient_revisies_insert_editor_of_hoger"
  on ingredient_revisies for insert
  to authenticated
  with check (is_editor_of_hoger());
